IF EXIST ci_version.h DEL /F ci_version.h
ECHO #ifndef CI_VERSION_H>ci_version.h
ECHO #define CI_VERSION_H>>ci_version.h
ECHO #define SPLAYER_VERSION_MAJOR 1 >>ci_version.h
ECHO #define SPLAYER_VERSION_MINOR 1 >>ci_version.h
ECHO #define SPLAYER_VERSION_PATCH 0 >>ci_version.h
ECHO #define SPLAYER_VERSION_BUILD %APPVEYOR_BUILD_NUMBER% >>ci_version.h
ECHO #ifndef ISPP_INVOKED>>ci_version.h
ECHO #define SPLAYER_VERSION_NUM   SPLAYER_VERSION_MAJOR,SPLAYER_VERSION_MINOR,SPLAYER_VERSION_PATCH,SPLAYER_VERSION_BUILD>>ci_version.h
ECHO #define SPLAYER_VERSION_STR   _T("%APPVEYOR_BUILD_VERSION%")>>ci_version.h
ECHO #define SPLAYER_COMMIT_ID_STR _T("%APPVEYOR_REPO_COMMIT%")>>ci_version.h
ECHO #define SPLAYER_COMMIT_AUTHOR_STR _T("%APPVEYOR_REPO_COMMIT_AUTHOR%")>>ci_version.h
ECHO #define SPLAYER_COMMIT_AUTHOR_EMAIL_STR _T("%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%")>>ci_version.h
ECHO #define SPLAYER_COMMIT_TIMESTAMP_STR _T("%APPVEYOR_REPO_COMMIT_TIMESTAMP%")>>ci_version.h
ECHO #define SPLAYER_COMMIT_MESSAGE_STR _T("%APPVEYOR_REPO_COMMIT_MESSAGE%")>>ci_version.h
ECHO #endif>>ci_version.h
ECHO #endif>>ci_version.h
IF EXIST version.pri DEL /F version.pri
ECHO VERSION=%APPVEYOR_BUILD_VERSION% >version.pri
