VERSION = 1.2.0
DEFINES += SUGOI_VERSION=\\\"$${VERSION}\\\"
win32 {
    QMAKE_TARGET_PRODUCT     = Sugoi Player
    QMAKE_TARGET_DESCRIPTION = Sugoi Player
    QMAKE_TARGET_COMPANY     = wangwenx190
    QMAKE_TARGET_COPYRIGHT   = GPLv3
}
